chainlink:
  image:
    image: public.ecr.aws/chainlink/chainlink
    version: 1.4.1-nonroot
  web_port: 6688
  p2p_port: 8090
  resources:
    requests:
      cpu: 350m
      memory: 1024Mi
    limits:
      cpu: 350m
      memory: 1024Mi
db:
  stateful: false
  capacity: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi
replicas: 1

env:
  database_url: postgresql://postgres:node@0.0.0.0/chainlink?sslmode=disable
  database_name: chainlink
  eth_url: ws://geth:8546
  eth_chain_id: "1337"
  allow_origins: '*'
  chainlink_dev: "true"
  feature_external_initiators: "false"
  chainlink_pgpassword: node
  chainlink_port: "6688"
  chainlink_tls_port: "0"
  feature_offchain_reporting: "true"
  json_console: "true"
  log_level: debug
  minimum_contract_payment_link_juels: "0"
  p2p_listen_ip: 0.0.0.0
  p2p_listen_port: "6690"
  root: ./clroot
  secure_cookies: "false"
  eth_max_in_flight_transactions: "16"
  keeper_registry_sync_interval: "5s"
  keeper_registry_perform_gas_overhead: "150000"
  keeper_turn_look_back: "0"
  explorer_url:
  explorer_access_key:
  explorer_secret:
  session_timeout: "999h"
