apiVersion: apps/v1
kind: Deployment
metadata:
  name: sol
spec:
  selector:
    matchLabels:
      app: sol
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: sol
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: vol
          configMap:
            name: sol-cm
      containers:
        - name: sol-val
          image: {{ .Values.sol.image.image }}:{{ .Values.sol.image.version }}
          volumeMounts:
            - mountPath: /root/.config/solana/cli
              name: vol
          ports:
            - name: http-rpc
              containerPort: 8899
            - name: ws-rpc
              containerPort: 8900
{{- if .Values.sol.resources }}
          resources:
{{ toYaml .Values.sol.resources | indent 12 }}
{{- end }}
          command: ["solana-test-validator"]
          args: ["-r", "--mint", "AAxAoGfkbWnbgsiQeAanwUvjv6bQrM5JS8Vxv1ckzVxg"]
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
