apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcd-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcd-api
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fcd-api
        release: {{ .Release.Name }}
    spec:
      containers:
        - args:
            - start
          env:
            - name: BYPASS_URI
              valueFrom:
                configMapKeyRef:
                  key: BYPASS_URI
                  name: fcd-env
            - name: CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  key: CHAIN_ID
                  name: fcd-env
            - name: LCD_URI
              valueFrom:
                configMapKeyRef:
                  key: LCD_URI
                  name: fcd-env
            - name: LEGACY_NETWORK
              valueFrom:
                configMapKeyRef:
                  key: LEGACY_NETWORK
                  name: fcd-env
            - name: RPC_URI
              valueFrom:
                configMapKeyRef:
                  key: RPC_URI
                  name: fcd-env
            - name: TYPEORM_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_CONNECTION
                  name: fcd-env
            - name: TYPEORM_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_DATABASE
                  name: fcd-env
            - name: TYPEORM_ENTITIES
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_ENTITIES
                  name: fcd-env
            - name: TYPEORM_HOST
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_HOST
                  name: fcd-env
            - name: TYPEORM_LOGGING
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_LOGGING
                  name: fcd-env
            - name: TYPEORM_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_PASSWORD
                  name: fcd-env
            - name: TYPEORM_SYNCHRONIZE
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_SYNCHRONIZE
                  name: fcd-env
            - name: TYPEORM_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: TYPEORM_USERNAME
                  name: fcd-env
            - name: USE_LOG_FILE
              valueFrom:
                configMapKeyRef:
                  key: USE_LOG_FILE
                  name: fcd-env
          image: terramoney/fcd:1.0.0-beta.2
          name: fcd-api
          ports:
            - name: fcd
              containerPort: 3060
{{- if .Values.fcd_api.resources }}
          resources:
{{ toYaml .Values.fcd_api.resources | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /app/logs
              name: fcd-api-cm0
      restartPolicy: Always
      volumes:
        - name: fcd-api-cm0
          emptyDir: {}
