apiVersion: v1
kind: Service
metadata:
  name: fcd-api
  labels:
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: "fcd"
      port: 3060
      targetPort: 3060
  selector:
    app: fcd-api
    release: {{ .Release.Name }}
