apiVersion: v1
kind: Service
metadata:
  name: geth
spec:
  selector:
    app: geth
    release: {{ .Release.Name }}
  ports:
  - name: ws-rpc
    port: 8546
    targetPort: ws-rpc
  - name: http-rpc
    port: 8544
    targetPort: http-rpc
  type: ClusterIP
