{{- if .Values.remote_test_runner.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: remote-runner-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.remote_test_runner.secrets }}
    {{- if $value }}
  {{ $key | upper}}: {{ $value | quote}}
    {{- end }}
  {{- end }}
{{- end }}
