kind: Service
apiVersion: v1
metadata:
  name: geth-{{ .Release.Name }}
  labels:
    app: geth-{{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: geth-{{ .Release.Name }}
  type: {{ .Values.geth.tx.service.type }}
  ports:
  - name: http-rpc
    port: 8544
    targetPort: 8544
  - name: ws-rpc
    port: 8546
    targetPort: 8546