apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-node-creds-secret
type: Opaque
data:
  nodepassword: VC50TEhrY213ZVBUL3AsXXNZdW50andIS0FzcmhtIzRlUnM0THVLSHd2SGVqV1lBQzJKUDRNOEhpbXdnbWJhWgo=
  apicredentials: bm90cmVhbEBmYWtlZW1haWwuY2huZmoyOTNmYkJubFEhZjl2TnM=
  node-password: VC50TEhrY213ZVBUL3AsXXNZdW50andIS0FzcmhtIzRlUnM0THVLSHd2SGVqV1lBQzJKUDRNOEhpbXdnbWJhWgo=