apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}-cm
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-cm
data:
  apicredentials: |
    notreal@fakeemail.ch
    twochains
  node-password: T.tLHkcmwePT/p,]sYuntjwHKAsrhm#4eRs4LuKHwvHejWYAC2JP4M8HimwgmbaZ
  init.sql: |
    CREATE EXTENSION pg_stat_statements;