apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-relay
  name: postgres-relay
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-relay
