apiVersion: v1
kind: Service
metadata:
  labels:
    app: terra-relay
    release: {{ .Release.Name }}
  name: terra-relay
spec:
  ports:
    - name: relay
      port: 6688
      targetPort: 6688
  selector:
    app: terra-relay
    release: {{ .Release.Name }}
