name: Linting
on:
  push:
    
jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - uses: smartcontractkit/tool-versions-to-env-action@v1.0.7
        id: go-version
      - run: echo ${{ steps.go-version.outputs.golang_version }}
      - name: Install Go ${{ steps.go-version.outputs.golang_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.golang_version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  vulnerabilities-check:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - uses: smartcontractkit/tool-versions-to-env-action@v1.0.7
        id: go-version
      - name: Install Go ${{ steps.go-version.outputs.golang_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.golang_version }}
      - name: Write Go List
        run: go list -json -deps ./... > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main

  helm-template-check:
    name: Verify Helm Template Formats
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - uses: smartcontractkit/tool-versions-to-env-action@v1.0.7
        id: tool-versions
      - uses: azure/setup-helm@v3.3
        with:
          version: ${{ steps.tool-versions.outputs.helm_version }}
      - name: Check templates
        run: make lint_helm_templates
      
  actionlint:
    name: Validate Github Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1.1.0
      - name: Run actionlint
        run: actionlint
