name: Linting
on:
  pull_request:
    branches: [master]
    
jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - uses: ./.github/actions/golang-version
        id: go-version
      - name: Install Go ${{ steps.go-version.outputs.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  vulnerabilities-check:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
      - uses: ./.github/actions/golang-version
        id: go-version
      - name: Install Go ${{ steps.go-version.outputs.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.go-version }}
      - name: Write Go List
        run: go list -json -deps ./... > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
